start-at-login = false

accordion-padding = 40

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[mode.main.binding]

    # navigate
    cmd-ctrl-h = 'focus left'
    cmd-ctrl-j = 'focus down'
    cmd-ctrl-k = 'focus up'
    cmd-ctrl-l = 'focus right'

    # move window
    ctrl-alt-shift-h = 'move left'
    ctrl-alt-shift-j = 'move down'
    ctrl-alt-shift-k = 'move up'
    ctrl-alt-shift-l = 'move right'

    ctrl-alt-shift-n = 'join-with left'
    ctrl-alt-shift-m = 'join-with down'
    ctrl-alt-shift-comma = 'join-with up'
    ctrl-alt-shift-period = 'join-with right'

    # resize
    ctrl-alt-minus = 'resize smart -50'
    ctrl-alt-equal = 'resize smart +50'
    ctrl-alt-enter = 'fullscreen'
    ctrl-alt-slash = 'layout accordion tiles'

    # multipler monitor
    # I should rarely use these because aerospace is only for single monitor setup

    #cmd-ctrl-leftSquareBracket = 'workspace --wrap-around prev'
    #cmd-ctrl-rightSquareBracket = 'workspace --wrap-around next'

    #cmd-ctrl-alt-leftSquareBracket = 'move-node-to-monitor --focus-follows-window --wrap-around prev'
    #cmd-ctrl-alt-rightSquareBracket = 'move-node-to-monitor --focus-follows-window --wrap-around next'
