# This group of options represents a command-line flag/option.  Flags explicitly
# added when running (ie: btm -a) will override this config file if an option
# is also set here.

[flags]
# Update rate
rate = 1000
# Lookback window of stored data
retention = "4h"
# Default lookback at startup
default_time_value = "5m"
# Amount of lookback changed upon zoom
time_delta = "5m"

[processes]
columns = ["pid", "name", "cpu%", "mem%", "time", "user"]

[[row]]
    ratio=3
[[row.child]]
    type="cpu"
    default=true

[[row]]
    ratio=4
[[row.child]]
    ratio=17
    type="mem"
[[row.child]]
    ratio=3
    type="net"

[[row]]
    ratio=3
[[row.child]]
    ratio=1
    type="proc"
[[row.child]]
    ratio=1
    type="disk"
