# LS
alias l='ls -l'
alias lt='ls -t'
alias la='ls -lA'
alias ld='ls -al | grep " \."'
alias las='ls -lASF'
alias ll='LC_COLLATE=en_US.ascii ls -l'
alias lss='ls --color | less -R'
alias lhid='ls -la | grep " \\."'

# Vim
alias vim='nvim'
alias vd='vim -d'
alias svim='sudo env "PATH=$PATH" nvim'
alias vs='vim -S Session.vim'
